Diplom 3
ksonic/Diplom_3 pull request #1
Opened 2022-05-15 16:08 UTC by ksonic

2022-05-17 06:35 UTC, nrasskosova requested changes

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/pageobject/LoginPage.java
> +    //локатор заголовка "Вход"
комментарий перепутан с комментарием для локатора Регистрация

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/pageobject/LoginPage.java
> +    public static SelenideElement AccountLoginButton;
использовать camel для переменной класса  - accountLoginButton

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/pageobject/RegistrationPage.java
> +    public static void setRegistrationForm(User user) {
Этот метод можно сделать возвращающим тип LoginPage. И в тестах проверять не по url, например, а метода loginPage.isOpened()

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/tests/RegistrationPageTest.java
> +        webdriver().shouldHave(url("https://stellarburgers.nomoreparties.site/login"));
Очень плохая практика указывать урлы прямо в тестах.
Если URL поменяется, то нужно будет внести изменения во все тесты и нигде не упустить. Нужно вынести все урлы в отдельный файл и сделать их static final

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/tests/LoginPageTest.java
> +       MainPage.mainPageLoginButtonClick();
используем объект mainPage для работы со страницой вместо статического метода. Метода open - делаем нестатическим

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/tests/LoginPageTest.java
> +                open(BASE_URL+"register",RegistrationPage.class);
относительные пути так же нужно хранить в переменных

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/tests/ConstructorPageTest.java
> +        RegistrationPage registrationPagePage =
все объекты страниц из этого метода выносим на уровень класса и используем их после инициализации  в @BeforeEach в тестах.

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/tests/LogoutTest.java
> +    public void LogoutTest() {
исправить название метода

2022-05-17 06:35 UTC, nrasskosova commented on src/test/java/tests/ConstructorSectionsTest.java
> +       saucesSection.parent().shouldHave(cssClass("tab_tab_type_current__2BEPc"));
проверку открытия можно сделать отдельным методом, чтоб каждый раз не вводить cssClass.
И тут кажется хорошая возмодность для параметризации теста)

2022-05-23 12:14 UTC, nrasskosova commented on src/main/java/pageobject/MainPage.java
> +    public static void saucesSectionClick() {
модификатор static излишен для этого метода.
еще раз хочу сделать упор на название методов. Первое слово в названиях методов должен быть глагол. Обращай внимание в своей работе автотестировщиком)

2022-05-23 12:17 UTC, nrasskosova commented on src/main/java/helper/YandexBrowserSetUp.java
> +        System.setProperty("webdriver.chrome.driver", "/Users/sofia/Stellar_Burgers_UI/yandexdriver");
ты указала путь до локального ресурса. Ресурсы, необходимые в проекте, нужно выкладывать в директорию src/resources и указывать путь до них. Выложи ресурс и измени путь

2022-05-23 12:20 UTC, nrasskosova commented on src/main/java/helper/YandexBrowserSetUp.java
> +    @BeforeEach
этот метод тут излишен, так как ты сразу вызываешь статический метод класса

2022-05-23 13:36 UTC, ksonic commented on src/main/java/pageobject/MainPage.java
> +    public static void saucesSectionClick() {
Поправила наименования методов.

2022-05-23 13:37 UTC, ksonic commented on src/main/java/helper/YandexBrowserSetUp.java
> +        System.setProperty("webdriver.chrome.driver", "/Users/sofia/Stellar_Burgers_UI/yandexdriver");
Поправила путь, выложила драйвер.

2022-05-23 13:38 UTC, ksonic commented on src/main/java/helper/YandexBrowserSetUp.java
> +    @BeforeEach
Забыла удалить. Уже убрала.

2022-05-23 15:07 UTC, nrasskosova commented
теперь ок. переводи задание в практикуме на ревью

2022-06-12 16:08 UTC, merged